import type { NextPage } from 'next'
import Head from 'next/head'
import { ArrowDownIcon } from '@parley-hub/aeolus';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ArrowDownIcon variant='info' size="9xl" />
      </main>
    </div>
  )
}

export default Home
